# Use the official Golang image for building the application
FROM golang:1.22.2 AS builder

# Set the working directory inside the container
WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod tidy

# Copy the rest of the application code
COPY . .

RUN go build -o authentication-service

# Copy the .env file if you need it inside the container
COPY .env .env

# Expose the port the service will run on
EXPOSE 8085

# Command to run the executable
CMD ["./authentication-service"]
