FROM golang:1.22.2 AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod tidy

COPY . .

RUN go build -o authentication-service

COPY .env .env

EXPOSE 8085

CMD ["./authentication-service"]
